# Generated by Django 4.2.9 on 2024-10-14 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_status', models.CharField(default='Pending', max_length=15)),
            ],
            options={
                'verbose_name': 'Đặt lịch',
                'verbose_name_plural': 'Đặt lịch',
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên địa điểm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí, tỉnh thành')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_dest_images/', verbose_name='Ảnh')),
                ('best_season', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mùa đẹp nhất để du lịch')),
            ],
            options={
                'verbose_name': 'Điểm đến du lịch',
                'verbose_name_plural': 'Điểm đến du lịch',
                'db_table': 'tourist_destination',
            },
        ),
        migrations.CreateModel(
            name='TourService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('service_type', models.IntegerField(choices=[(0, 'Nhà xe'), (1, 'Công ty du lịch'), (2, 'Tuyến tàu'), (3, 'Vé máy bay')], default=0, verbose_name='Loại dịch vụ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Giá dịch vụ')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thông tin liên hệ')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Dịch vụ du lịch',
                'verbose_name_plural': 'Dịch vụ du lịch',
                'db_table': 'tourist_service',
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('departure', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('service_provider', models.ForeignKey(db_column='service_provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tourservice')),
            ],
            options={
                'verbose_name': 'Lộ trình',
                'verbose_name_plural': 'Lộ trình',
                'db_table': 'transport_route',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.IntegerField(choices=[(0, 'ATM'), (1, 'Cash'), (2, 'Internet Banking')], default=0)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=15)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tourservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.touristdestination'),
        ),
    ]
