# Generated by Django 4.2.9 on 2024-10-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transportroute_options_remove_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='Các hoạt động như ăn uống, khách sạn, hướng dẫn viên du lịch, vé vui chơi, ...', max_length=255, verbose_name='Tên hoạt động'),
        ),
    ]
