# Generated by Django 4.2.9 on 2024-10-14 05:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_description_alter_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Chi tiết địa điểm'),
        ),
        migrations.AddField(
            model_name='touristdestination',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email khách hàng'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=15, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.touristdestination', verbose_name='Điểm đến du lịch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transportroute', verbose_name='Tour du lịch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'ATM'), (1, 'Cash'), (2, 'Internet Banking')], default=0, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=15, verbose_name='Trạng thái thanh toán'),
        ),
    ]
