# Generated by Django 4.2.9 on 2024-10-14 16:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourservice',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='service_banner/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Giới thiệu'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='hotline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hotline'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Giá dịch vụ từ'),
        ),
    ]
